
name: 'tp_final_ad'
version: '1.0.0'


profile: 'tp_final_ad'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  tp_final_ad:
    marts:
      +materialized: table
    facts:
      +materialized: table
    dimensions:
      +materialized: table
    staging:
      +materialized: table

seeds:
  tp_final_ad:
    data:
      header: true
      delimiter: ","
      quote_columns: true
    tempo:
      header: true
      delimiter: ","
      quote_columns: true
    base_bruta_acidentes:
      header: true
      delimiter: ","
      quote_columns: true